INSERT INTO sys_usergroup (objid,title,domain,role) 
VALUES ('FINANCIAL.ADMIN', 'FINANCIAL ADMIN', 'FINANCIAL', 'ADMIN' ),
('FINANCIAL.MASTER', 'FINANCIAL MASTER', 'FINANCIAL', 'MASTER' ),
('FINANCIAL.REPORT', 'FINANCIAL REPORT', 'FINANCIAL', 'REPORT' );
